name: Publish to package managers
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'release tag to publish (e.g. 1.0.1)'
        required: true
jobs:
  homebrew:
    runs-on: macos-latest
    steps:
    - name: bump cask pr
      env:
        # zizmor: ignore[secrets-outside-env] TODO
        HOMEBREW_GITHUB_API_TOKEN: "${{ secrets.HOMEBREW_TOKEN }}"
        version: ${{ github.event.release.tag_name || github.event.inputs.version }}
      run: |
        brew tap hackmajoris/apps
    	brew trust hackmajoris/apps
        brew bump-cask-pr rebased --version $version